select
ORDERID,
ORDERDATE,
CUSTOMERID,
EMPLOYEEID,
STOREID,
STATUS AS STATUSCD,
CASE WHEN STATUS = '01' THEN 'IN PROGRESS'
     WHEN STATUS = '02' THEN 'COMPLETED'
	 WHEN STATUS = '03' THEN 'CANCELLED'
	 ELSE NULL
END AS STATUSDESC,
CASE WHEN STOREID = 1000 THEN 'ONLINE'
     ELSE 'IN STORE'
END AS ORDER_CHANNEL,
Updated_at
FROM {{source('landing','ordr')}}